# Generated by Django 3.1.7 on 2021-03-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='div',
            new_name='division',
        ),
    ]
